version: '2'
services:
  icinga2:
    image: jerenius/icinga2
    restart: on-failure:5
    hostname: icinga2
    environment:
      - ICINGA2_FEATURE_GRAPHITE=1
      # Important:
      # keep the hostname graphite the same as
      # the name of the graphite docker-container
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      - ICINGAWEB2_ADMIN_USER=admin
      - ICINGAWEB2_ADMIN_PASS=icinga
      #- ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
    ports:
      - "80:80"
      - "5665:5665"
      - "3306:3306"
    volumes:
      - /opt/icinga2/etc:/etc/icinga2
      - /opt/icinga2/lib:/var/lib/icinga2
      - /opt/icinga2/log:/var/log/icinga2
      - /opt/icinga2/mysql:/var/lib/mysql
  graphite:
    image: sitespeedio/graphite:latest
    restart: on-failure:5
    hostname: graphite
    ports:
    - "2003:2003"
    - "8080:80"
    volumes:
      - ./graphite/lib:/var/lib/graphite
      - ./graphite/log/apache:/var/log/apache2
      - ./graphite/log/graphite:/var/log/graphite
      - ./graphite/log/carbon:/var/log/carbon
