#!/bin/bash

service ssh start

# Allow any signal which would kill a process to stop server
trap "service ssh stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u root ssh > /dev/null; do sleep 5; done
